//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMEWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ReportInsRegLimitValue
    {
        public string InstrumentEid { get; set; }
        [Required]
        [DisplayName("Start Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM-dd-yyyy}")]
        public System.DateTime ReportInsRegLimitValueScdStartDate { get; set; }
        [Required]
        [DisplayName("End Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM-dd-yyyy}")]
        public System.DateTime ReportInsRegLimitValueScdEndDate { get; set; }
        [DisplayName("Current Indicator")]
        public bool ReportInsRegLimitValueScdCurrentIndicator { get; set; }
        [DisplayName("PreCleared Indicator")]
        public string InstrumentPreClearedIndicator { get; set; }
        [DisplayName("Limit Percentage")]
        public decimal InsRegLimitPercentage { get; set; }
        [DisplayName("Note")]
        public string NoteText { get; set; }
        [DisplayName("Context TypeCode ")]
        public string InputIdContextTypeCode { get; set; }
        [DisplayName("Instrument ID")]

        public string InputInstrumentId { get; set; }

        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
    }
}
